name = "phaestus"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "phaestus"
database_id = "57a03632-4d39-4504-9c34-731b4c58db4a"

# R2 Storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "phaestus-assets"

[vars]
ENVIRONMENT = "development"
